### ISSUE TITLE
several files is not exist

### ISSUE THREAD

**Issue by da0ka** [aldo-gutierrez/bitmasksorter#1]
com.aldogg.sorter.intType.mt is not exist

**Comment by aldo-gutierrez** [comment]
I will check it

**Comment by da0ka** [comment]
I'm sorry, those are exists!

**Comment by aldo-gutierrez-tierconnect-com** [comment]
Hi can you provide the error message.
I just tried git cloning and building with gradle with 'gradle clean assemble' in Windows and Ubuntu 20.04 WSL2 and it doesn't throw any error.
